In [2]:
import torch

### 基础操作

In [12]:
# 张量创建
# 行张量
x = torch.arange(10)
# 全0,1,高斯分布张量
torch.zeros((3, 4))
torch.ones((3, 4))
torch.randn((3, 4))  # 其中的每个元素都从均值为0、标准差为1的标准高斯分布中随机采样
# 从列表转换
torch.tensor([[1, 2, 3], [4, 5, 6]])

# 形状
x.shape
# 元素个数
x.numel()
# 形状改变
x.reshape(2, 5)
x.reshape(-1, 5)  # -1表示自动推断维度

tensor([[-0.2239, -0.0394,  0.7119, -2.0329],
        [-0.5292,  0.0525, -0.6500,  0.4735],
        [-2.1330,  0.5324,  0.6157, -1.2672]])

### 运算

In [16]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 6, 7])

# 对应元素运算
x + y, x - y, x * y, x ** y, x / y
# e指数
torch.exp(x)

# 连结张量
x = torch.arange(12).reshape((3, 4))
y = torch.tensor([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
torch.cat((x, y), dim=0)  # 改变第0个维度(对于矩阵来说是行)
torch.cat((x, y), dim=1)  # 改变第1个维度(对于矩阵来说是列)

# 元素求和
x.sum()
# 比较张量
x == y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### 广播机制

In [29]:
# 在两个张量每个维度下元素个数不同时,广播机制会自动将较小元素个数的张量自动复制,从而使得两个张量同一维度下的元素个数相匹配
x = torch.arange(3).reshape((1, 3))
y = torch.arange(2).reshape((2, 1))
x + y

tensor([[0, 1, 2],
        [1, 2, 3]])

### 索引和切片

In [33]:
# [行, 列]
# :表示范围选取
x = torch.arange(12).reshape((3, 4))
x[:, 3]
x[:, 0:2]
# 赋值
x[1, :] = 10

IndexError: too many indices for tensor of dimension 2

### 内存

In [35]:
# 使用X[:] = X + Y或X += Y来减小内存消耗
# 这两种方式不具有广播机制
x = torch.arange(3).reshape((1, 3))
y = torch.arange(3).reshape((1, 3))

before = id(x)
x += y
before == id(x)

True

### 转换为其他Python对象

In [38]:
import numpy as np
x = torch.arange(3).reshape((1, 3))
y = torch.tensor([1])

# 转换为numpy对象
x.numpy()
# 大小为1的张量转化为python数据类型
y.item(), int(y), float(y)

(1, 1, 1.0)