In [1]:
import torch

### 反向模式进行自动求导

In [8]:
# 让张量为梯度分配内存
x = torch.tensor([1, 1, 1, 1], dtype=torch.float32, requires_grad=True)  # 等价于x.requires_grad_(True)
y = 2 * torch.dot(x, x)
# 对y进行反向传播
y.backward()
# 获取梯度
x.grad
x.grad == 4 * x

tensor([1., 1., 1., 1.])

In [9]:
# 注意清空梯度: 在默认情况下PyTorch会累积梯度,我们需要清除之前的值后才能计算其他的梯度
x.grad.zero_()
z = x.sum()
z.backward()
x.grad

tensor([1., 1., 1., 1.])

### 将某个变量驱逐出计算图

In [12]:
x = torch.tensor([1, 1, 1, 1], dtype=torch.float32, requires_grad=True)
y = x * x
u = y.detach()  # 分离y来返回一个新变量u,该变量与y具有相同的值,但丢弃计算图中如何计算y的任何信息
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])