In [1]:
import torch
from torch import nn
from torch.nn import functional as F

tmp_path = './_tmp_files/x-file'
tmp_model_path = './_tmp_files/mlp.params'

### 加载和保存张量

#### 存储并读取张量

In [2]:
x = torch.arange(4)
# save方法必须现有这个文件才能存储
torch.save(x, tmp_path)
x2 = torch.load(tmp_path)
x2

tensor([0, 1, 2, 3])

#### 存储张量列表

In [3]:
y = torch.zeros(4)
torch.save([x, y], tmp_path)
x2, y2 = torch.load(tmp_path)
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

#### 存储张量字典

In [4]:
x, y = torch.arange(4), torch.zeros(4)
mydict = {'x': x, 'y': y}
torch.save(mydict, tmp_path)
mydict2 = torch.load(tmp_path)
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

### 加载和保存模型：加载和保存模型参数

In [5]:
# 自定义模型
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))


net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [6]:
# 保存模型参数
torch.save(net.state_dict(), tmp_model_path)
clone = MLP()
clone.load_state_dict(torch.load(tmp_model_path))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [7]:
# 验证保存与读取的正确性
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])