### 概念

* 作用：因为卷积层对位置过于敏感，池化层用来缓解这种敏感
* 特性
    * 池化层与卷积层类似，都具有填充和步幅
    * 没有可学习的参数，但有窗口大小、填充与步幅这三个超参数
    * 在每个输入通道应用池化层以获得相应的输出通道
    * 输出通道数=输入通道数
* 类型
    * 最大池化层：选取每个窗口的最大值
    * 平均池化层：计算每个窗口的平均值

### 代码

In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
# 定义池化层操作
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [4]:
# 最大池化层
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [5]:
# 平均池化层
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [7]:
# 设定步幅与填充
X = torch.arange(16, dtype=d2l.float32).reshape((1, 1, 4, 4))
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [9]:
# 输入通道数=输出通道数
X = torch.cat((X, X + 1), 1)
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
X, pool2d(X)

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],
 
          [[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10., 11., 12.],
           [13., 14., 15., 16.]],
 
          [[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10., 11., 12.],
           [13., 14., 15., 16.]],
 
          [[ 2.,  3.,  4.,  5.],
           [ 6.,  7.,  8.,  9.],
           [10., 11., 12., 13.],
           [14., 15., 16., 17.]]]]),
 tensor([[[[ 5.,  7.],
           [13., 15.]],
 
          [[ 6.,  8.],
           [14., 16.]],
 
          [[ 6.,  8.],
           [14., 16.]],
 
          [[ 7.,  9.],
           [15., 17.]]]]))